### ISSUE TITLE
Method to find the open pull request is not working as expected

### ISSUE THREAD

**Issue by crqra** [carlsberg/gh-releaser#1]
The existing implementation returns every Pull Request with the `gh-releaser` label, regardless of the repository. This creates a wrong behavior where open PRs from other repositories are also returned.

The method [`findPullRequests`](https://github.com/carlsberg/gh-releaser/blob/494186f6557bb281f68b1f481e5df531a77920d6/lib/mod.ts#L152) should use the [list issues endpoint](https://docs.github.com/en/rest/reference/issues#list-repository-issues) instead, so only issues from the current repository are listed.

After retrieving the issues we need to additionally filter them to have only Pull Requests and remove issues. Example:

```ts
let pullRequests = issues.filter(issue => issue.pull_request);
```

**Comment by jsmvaldivia** [comment]
Instead of using the list issues endpoint, I opted for the [list pulls endpoint](https://docs.github.com/en/rest/reference/pulls).
It avoids the filtering part.

**Comment by crqra** [comment]
The [list pulls endpoint](https://docs.github.com/en/rest/reference/pulls) doesn't allow filtering by labels, unfortunately. You can still use it to avoid filtering issues from pull requests and apply the filter to the pull request labels (i.e. `.filter(pr => pr.labels.includes("gh-releaser"))`).
