### ISSUE TITLE
Github rebase puts branches out of sync

### ISSUE THREAD

**Issue by jsmvaldivia** [carlsberg/gh-releaser#32]
[Documentation](https://docs.github.com/en/github/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#rebase-and-merge-your-pull-request-commits)

As per the above documentation 

> The rebase and merge behavior on GitHub deviates slightly from git rebase. Rebase and merge on GitHub will always update the committer information and create new commit SHAs, whereas git rebase outside of GitHub does not change the committer information when the rebase happens on top of an ancestor commit. For more information about git rebase, see the official Git documentation.

Even though we have the same commits in a release branch created when rebasing it to master and then to develop it has essentially different commits.

Using merge mode will always put develop a commit ahead but it will stay like that all the way.
Probably the last solution I can think of is setting the merge manually with libgit or alike

**Comment by crqra** [comment]
I agree that the way to go is through using `libgit2`. Unfortunately there isn't any implementation in Deno ([deno-git](https://deno.land/x/git@v0.0.1) is WIP but doesn't has any commit for the past 14 months).

We can try using [nodegit](https://github.com/nodegit/nodegit) (Node.js `libgit2` implementation) though I'm not sure if it will work. Looking at the [Skypack](https://www.skypack.dev/view/nodegit) page they don't have an ES Entry Point, nor Export Map, nor TS types (available at [@types/nodegit](https://www.skypack.dev/view/@types/nodegit)).

I wonder if the best and simplest solution for our current problem is to just use the `git` CLI directly with `Deno.run`:

```typescript
Deno.run({ cmd: ["git", "rebase"] });
```

**Comment by jsmvaldivia** [comment]
That seems to be the way to go, I didn't know you could do that with Deno but it sounds like it is the least dependable way of doing this

**Comment by jsmvaldivia** [comment]
I was thinking all along, biased by the Github Pull Request API that we could merge with rebase.
Actually, it works with pulls.
https://git-scm.com/docs/git-merge
